import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsPortfolio: SidebarsConfig = {
  portfolioSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Documentation Portfolio',
    },

    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'case-studies',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },

    {
      type: 'category',
      label: 'Technical Guides',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-guides',
        },
      ],
    },

    {
      type: 'category',
      label: 'API Documentation',
      collapsed: true,
      items: [
    {
        type: 'category',
        label: "Beginner's Guide",
        collapsed: true,
        items: [
        {
          type: 'autogenerated',
          dirName: 'api/Beginner\'s Guide',
        },
      ],
    },

    {
      type: 'category',
      label: 'Before You Write',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/Before You Write',
        },
      ],
    },

    {
      type: 'category',
      label: 'Writing API Documentation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/Writing API Documentation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Advanced API Documentation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/Advanced API Documentation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Real-World API Example',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/Real-World API Example',
        },
      ],
    },

    {
      type: 'category',
      label: 'Release Management API',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/release-management',
        },
         ],
        },
      ],
    },
  ],
};

export default sidebarsPortfolio;