import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learningPath: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Start Here',
    },

    {
      type: 'category',
      label: 'Module 1 · Welcome',
    
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '00-Welcome',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 2 · Environment Setup',
    
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-Environment-Setup',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 3 · Markdown',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-Markdown',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 4 · Git',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '03-Git',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 5 · GitHub',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-GitHub',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 6 · Docs-as-Code Workflow',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '05-Docs-as-Code-Workflow',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 7 · Static Site Generators',
     
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '06-Static-Site-Generators',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 8 · Docusaurus',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '07-Docusaurus',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 9 · API Documentation',
     
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '08-API-Documentation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 10 · AI',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '09-AI',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 11 · Automation',
     
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '10-Automation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 12 · AI for Technical Writers',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '11-AI-For-Technical-Writers',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 13 · Real-World Projects',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '12-Real-World-Projects',
        },
      ],
    },

    {
      type: 'category',
      label: 'Appendix',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendix',
        },
      ],
    },

    {
      type: 'category',
      label: 'Glossary',
      
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'glossary',
        },
      ],
    },
    {
  type: 'category',
  label: 'Showcase',
  items: [
    'showcase/ai-release-note-generator/index',
      ],
    },
  ],
};

export default sidebars;