import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learningPath: [
    {
  type: 'doc',
  id: 'intro',
  label: '🏠 Start Here',
},

    {
      type: 'category',
      label: '👋 Module 1 · Welcome',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '00-Welcome',
        },
      ],
    },

    {
      type: 'category',
      label: '💻 Module 2 · Environment Setup',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-Environment-Setup',
        },
      ],
    },

    {
      type: 'category',
      label: '📝 Module 3 · Markdown',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-Markdown',
        },
      ],
    },

    {
      type: 'category',
      label: '🌿 Module 4 · Git',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '03-Git',
        },
      ],
    },

    {
      type: 'category',
      label: '🐙 Module 5 · GitHub',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-GitHub',
        },
      ],
    },
    
    {
      type: 'category',
      label: '📚 Module 6 · Docs-as-Code Workflow',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '05-Docs-as-Code-Workflow',
        },
      ],
    },

    {
      type: 'category',
      label: '🌐 Module 7 · Static Site Generators',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '06-Static-Site-Generators',
        },
      ],
    },

    {
      type: 'category',
      label: '🦖 Module 8 · Docusaurus',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '07-Docusaurus',
        },
      ],
    },

    // Continue the same pattern for Modules 6–13

  ],
};

export default sidebars;