import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learningPath: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Start Here',
    },

    {
      type: 'category',
      label: 'Module 1 · Welcome',
      link: {
        type: 'doc',
        id: 'Welcome/README',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '00-Welcome',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 2 · Environment Setup',
      link: {
        type: 'doc',
        id: 'Environment-Setup/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-Environment-Setup',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 3 · Markdown',
      link: {
        type: 'doc',
        id: 'Markdown/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-Markdown',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 4 · Git',
      link: {
        type: 'doc',
        id: 'Git/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '03-Git',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 5 · GitHub',
      link: {
        type: 'doc',
        id: 'GitHub/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-GitHub',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 6 · Docs-as-Code Workflow',
      link: {
        type: 'doc',
        id: 'Docs-as-Code-Workflow/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '05-Docs-as-Code-Workflow',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 7 · Static Site Generators',
      link: {
        type: 'doc',
        id: 'Static-Site-Generators/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '06-Static-Site-Generators',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 8 · Docusaurus',
      link: {
        type: 'doc',
        id: 'Docusaurus/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '07-Docusaurus',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 9 · API Documentation',
      link: {
        type: 'doc',
        id: 'API-Documentation/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '08-API-Documentation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 10 · AI',
      link: {
        type: 'doc',
        id: 'AI/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '09-AI',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 11 · Automation',
      link: {
        type: 'doc',
        id: 'Automation/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '10-Automation',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 12 · AI for Technical Writers',
      link: {
        type: 'doc',
        id: 'AI-For-Technical-Writers/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '11-AI-For-Technical-Writers',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 13 · Real-World Projects',
      link: {
        type: 'doc',
        id: 'Real-World-Projects/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '12-Real-World-Projects',
        },
      ],
    },

    {
      type: 'category',
      label: '📚 Appendix',
      link: {
        type: 'doc',
        id: 'appendix/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendix',
        },
      ],
    },

    {
      type: 'category',
      label: '📖 Glossary',
      link: {
        type: 'doc',
        id: 'glossary/README',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'glossary',
        },
      ],
    },
  ],
};

export default sidebars;