import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsPortfolio: SidebarsConfig = {
  portfolioSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Documentation Portfolio',
    },

    {
      type: 'category',
      label: 'Case Studies',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'case-studies',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },

    {
      type: 'category',
      label: 'Technical Guides',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-guides',
        },
      ],
    },

    {
      type: 'category',
      label: 'API Documentation',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/release-management/release-management-api',
          label: 'Release Management API',
        },

        {
          type: 'doc',
          id: 'api/release-management/getting-started',
          label: 'Getting Started',
        },
        {
          type: 'doc',
          id: 'api/release-management/authentication',
          label: 'Authentication',
       },
       {
          type: 'doc',
          id: 'api/release-management/api-reference',
          label: 'API Reference',
        },
      ],
    },
  ],
};

export default sidebarsPortfolio;