import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsPortfolio: SidebarsConfig = {
  portfolioSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Documentation Portfolio',
    },

    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'case-studies',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },

    {
      type: 'category',
      label: 'Technical Guides',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-guides',
        },
      ],
    },

    {
      type: 'category',
      label: 'API Documentation',
      collapsed: false,
      items: [
       {
          type: 'autogenerated',
          dirName: 'api',
       },
    ],
   },
  ],
};

export default sidebarsPortfolio;